apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: spinder
  namespace: default
  labels:
    team: tbd
spec:
  image: navikt/spinder:bLiRbYtTaUt
  port: 7000
  team: tbd
  liveness:
    path: /isalive
    initialDelay: 20
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: /isready
    initialDelay: 20
    timeout: 1
  resources:
    limits:
      cpu: 2000m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 128Mi
  ingresses:
  - https://spinder.nais.preprod.local
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  prometheus:
    enabled: true
    path: /metrics
  secrets: false